language: node_js

node_js:
- "node"
- "lts/*"

branches:
  only:
  - master

os:
- linux
- osx

before_script:
- chmod +x ./bash_scripts/travis-build.sh

script: ./bash_scripts/travis-build.sh

notifications:
  email:
    on_success: never
    on_failure: change
